export type Mahasiswa = {
  nama: string;
  nilai: Record<string, number>;
};

export const mockMahasiswaPerKelas: Record<string, Mahasiswa[]> = {
  "1": [
    { nama: "Tobio Kageyama", nilai: {} },
    { nama: "Nezuko Kamado", nilai: {} },
    { nama: "Monkey D. Luffy", nilai: {} },
    { nama: "Naruto Uzumaki", nilai: {} },
    { nama: "Sasuke Uchiha", nilai: {} },
    { nama: "Sakura Haruno", nilai: {} },
    { nama: "Light Yagami", nilai: {} },
    { nama: "Lelouch Lamperouge", nilai: {} },
    { nama: "Edward Elric", nilai: {} },
    { nama: "Alphonse Elric", nilai: {} },
    { nama: "Levi Ackerman", nilai: {} },
    { nama: "Mikasa Ackerman", nilai: {} },
    { nama: "Eren Yeager", nilai: {} },
    { nama: "Armin Arlert", nilai: {} },
    { nama: "Historia Reiss", nilai: {} },
  ],
  "2": [
    { nama: "Killua Zoldyck", nilai: {} },
    { nama: "Zenitsu Agatsuma", nilai: {} },
    { nama: "Tanjiro Kamado", nilai: {} },
    { nama: "Obanai Iguro", nilai: {} },
    { nama: "Reiner Braun", nilai: {} },
    { nama: "Annie Leonhart", nilai: {} },
    { nama: "Bertholdt Fuber", nilai: {} },
    { nama: "Ymir Fritz", nilai: {} },
    { nama: "Erwin Smith", nilai: {} },
    { nama: "Hange Zoe", nilai: {} },
    { nama: "Jean Kirstein", nilai: {} },
    { nama: "Conny Springer", nilai: {} },
    { nama: "Sasha Blouse", nilai: {} },
    { nama: "Marco Bott", nilai: {} },
    { nama: "Gabi Braun", nilai: {} },
    { nama: "Falco Grice", nilai: {} },
    { nama: "Pieck Finger", nilai: {} },
  ],
  "3": [
    { nama: "Tengen Uzui", nilai: {} },
    { nama: "Kyojuro Rengoku", nilai: {} },
    { nama: "Reiner Braunn", nilai: {} },
    { nama: "Zeke Yeager", nilai: {} },
    { nama: "Yelena Belova", nilai: {} },
    { nama: "Onyankopon", nilai: {} },
    { nama: "Hanji Zoe", nilai: {} },
    { nama: "Petra Rall", nilai: {} },
    { nama: "Erwin Smith", nilai: {} },
    { nama: "Hange Zoe", nilai: {} },
    { nama: "Shigeru Shingeki", nilai: {} },
    { nama: "Dot Pixis", nilai: {} },
    { nama: "Nile Dok", nilai: {} },
    { nama: "Djel Sankis", nilai: {} },
    { nama: "Kenny Ackerman", nilai: {} },
    { nama: "Rod Reiss", nilai: {} },
    { nama: "Uri Reiss", nilai: {} },
    { nama: "Frieda Reiss", nilai: {} },
    { nama: "Carla Yeager", nilai: {} },
    { nama: "Faye Yeager", nilai: {} },
    { nama: "Zeke Yeager", nilai: {} },
    { nama: "Mikasa Ackerman", nilai: {} },
  ],
  "4": [
    { nama: "Gon Freecss", nilai: {} },
    { nama: "Kurapika", nilai: {} },
    { nama: "Roronoa Zoro", nilai: {} },
    { nama: "Usopp", nilai: {} },
    { nama: "Nico Robin", nilai: {} },
    { nama: "Dracule Mihawk", nilai: {} },
    { nama: "Historia Reiss", nilai: {} },
    { nama: "Annie Leonhart", nilai: {} },
    { nama: "Bertholdt Hoover", nilai: {} },
    { nama: "Reiner Braun", nilai: {} },
    { nama: "Falco Grice", nilai: {} },
    { nama: "Gabi Braun", nilai: {} },
    { nama: "Pieck Finger", nilai: {} },
    { nama: "Ymir Fritz", nilai: {} },
    { nama: "Eren Yeager", nilai: {} },
    { nama: "Levi Ackerman", nilai: {} },
  ],
  "5": [
    { nama: "Gon Freecss", nilai: {} },
    { nama: "Kurapika", nilai: {} },
    { nama: "Roronoa Zoro", nilai: {} },
    { nama: "Usopp", nilai: {} },
    { nama: "Nico Robin", nilai: {} },
    { nama: "Dracule Mihawk", nilai: {} },
    { nama: "Armin Arlert", nilai: {} },
    { nama: "Erwin Smith", nilai: {} },
    { nama: "Hange Zoe", nilai: {} },
    { nama: "Jean Kirstein", nilai: {} },
    { nama: "Conny Springer", nilai: {} },
    { nama: "Sasha Blouse", nilai: {} },
    { nama: "Marco Bott", nilai: {} },
    { nama: "Hanji Zoe", nilai: {} },
    { nama: "Petra Rall", nilai: {} },
    { nama: "Dot Pixis", nilai: {} },
    { nama: "Nile Dok", nilai: {} },
    { nama: "Djel Sankis", nilai: {} },
    { nama: "Carla Yeager", nilai: {} },
  ],
};
